[build]
  command = "npm run build:netlify"
  publish = "public"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/"
  to = "/controller/"
  status = 302
